### ISSUE TITLE
spitting out arrayoutofboundsexception every 1ms

### ISSUE THREAD

**Issue by Vainiven** [SimplebotMS/Ikov#3]
java.lang.ArrayIndexOutOfBoundsException: Index 6210 out of bounds for length 161
	at k2.b(Unknown Source)
	at k2.a(Unknown Source)
	at k2.a(Unknown Source)
	at kg.getObjectDefinition(Unknown Source)
	at simple.api.SimpleDefinitions.getObjectDefinition(SimpleDefinitions.java)
	at simple.api.wrappers.SimpleSceneObject.<init>(SimpleSceneObject.java)
	at simple.api.wrappers.SimpleGameObject.<init>(SimpleGameObject.java)
	at simple.api.filters.SimpleObjects.r(SimpleObjects.java)
	at simple.api.filters.SimpleObjects.v(SimpleObjects.java)
	at simple.api.filters.SimpleObjects.list(SimpleObjects.java)
	at simple.api.queries.SimpleQuery.B(SimpleQuery.java)
	at simple.api.queries.SimpleQuery.populate(SimpleQuery.java)
	at skills.Thieving.grind(Thieving.java:20)
	at skills.Thieving.grind(Thieving.java:1)
	at skills.models.VSkill.handle(VSkill.java:128)
	at skills.models.VSkill.run(VSkill.java:93)
	at Bot.SkillScript.onProcess(SkillScript.java:111)
	at simple.bot.dU.c(dU.java)
	at simple.bot.dU.lambda$startScript$2(dU.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by the-zalox** [comment]
not our api, not sure we can do about this?
